/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package packageyay;

public class Launcher {
	
    public static void main(String[] args) {
        //Makes a new building
    	
    }
}
